Dt = input ('Digite o Ø do tambor [m]: ');
dca = input ('Digite o Ø do cabo de aço [m]: ');
Vlt = input ('Digite a velocidade linear do tambor [m/min]: ');
m = input ('Digite a massa a ser elevada [Kg]: ');
z1 = 0.025;
z2 = 0.075;
z3 = 0.025;
z4 = 0.1;
z5 = 0.05;
z6 = 0.15;
d1 = 0.01;
d2 = 0.05;
rpmt = (Vlt)/(pi*Dt);
Tt = (m*10)*(Dt/2);
cdr = (((((z6*rpmt)/z5)*z4)/z3)*z2)/z1;
rpmm = (cdr*d2)/d1;
disp ('A rotação no motor em RPM é de: ');
disp (rpmm);
Tm = (d1*Tt)/Dt;
P = (2*pi*rpmm*Tm)/(60*75);
disp (P);
